### ISSUE TITLE
npm install and start issue on window 10

### ISSUE THREAD

**Issue by orlandodemauro** [colinskow/angular-electron-dream-starter#5]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

Running npm istall is generating an error

hi first of all compliment for your work. I´m trying to run in and after run npm install I´m getting the following error:

> fcopy-pre-bundled@0.1.2 install C:\git\angular-electron-dream-starter\node_modules\fcopy-pre-bundled
> node-gyp rebuild

C:\git\angular-electron-dream-starter\node_modules\fcopy-pre-bundled>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\git\angular-electron-dream-starter\node_modules\fcopy-pre-bundled) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\angular-electron-dream-starter\node_modules\fcopy-pre-bundled
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
angular-electron-dream-starter@6.1.1 C:\git\angular-electron-dream-starter
`-- UNMET PEER DEPENDENCY chai@4.1.0

I fixed it upgrating electron-builder to 19.2.5. 

* **Please tell us about your environment:**

window 10, node 6.11.0 and npm 3.10.10

**Comment by colinskow** [comment]
Thanks for reporting, I will upgrade to the latest Electron and Electron-Builder in the next release.

**Comment by savarex** [comment]
Hi Orlando,
I had similar issues on my machine (same os and npm version).

After some tries, I solved them simply upgrading npm.

Please, try to update your npm to latest (or at least 5.x)

You can do that easily with the following command:
npm install -g npm

It should be enough ;)

Emanuele




On 14 Jul 2017 12:42, "orlando de mauro" <notifications@github.com> wrote:

*Note: for support questions, please use one of these channels:* Chat:
AngularClass.slack <http://angularclass.com/member-join/> or Twitter:
@AngularClass <https://twitter.com/AngularClass>

   -

   *I'm submitting a ...*
   [x] bug report
   [ ] feature request
   [ ] question about the decisions made in the repository
   -

   *Do you want to request a feature or report a bug?*

Report a bug.

   - *What is the current behavior?*

Running npm istall is generating an error

hi first of all compliment for your work. I´m trying to run in and after
run npm install I´m getting the following error:

fcopy-pre-bundled@0.1.2 install C:\git\angular-electron-dream-
starter\node_modules\fcopy-pre-bundled
node-gyp rebuild

C:\git\angular-electron-dream-starter\node_modules\fcopy-pre-bundled>if not
defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\
bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else
(node "" rebuild )
gyp: binding.gyp not found (cwd: C:\git\angular-electron-dream-
starter\node_modules\fcopy-pre-bundled) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (C:\Program
Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit
(internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program
Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\git\angular-electron-dream-starter\node_modules\fcopy-
pre-bundled
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
angular-electron-dream-starter@6.1.1 C:\git\angular-electron-dream-starter
`-- UNMET PEER DEPENDENCY chai@4.1.0

I fixed it upgrating electron-builder to 19.2.5. after that all he modules
are installed I´m getting the following issue running npm start

[at-loader] Checking started in a separate process... 79ms emitting
Hash: 3007e95f0b2edcbef469
Version: webpack 2.6.1
Time: 2026ms
Asset Size Chunks Chunk Names
index.js 7.89 kB 0 [emitted] index
index.js.map 7.81 kB 0 [emitted] index
[1] ./src/electron/index.ts 2.22 kB {0} [built]
[] -> factory:11ms building:134ms = 145ms
[2] ./src/electron/dev-extensions.ts 808 bytes {0} [built]
[] -> factory:10ms building:27ms dependencies:0ms = 37ms
[3] ./src/main.electron.ts 57 bytes {0} [built]
factory:33ms building:1716ms = 1749ms
+ 5 hidden modules
"undefined" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\git\angular-electron-dream-starter\node_modules\cross-
spawn\lib\enoent.js:11
err = new Error(syscall + ' ' + command + ' ENOENT');
^
Error: spawn undefined ENOENT
at notFoundError (C:\git\angular-electron-dream-starter\node_modules\
cross-spawn\lib\enoent.js:11:11)
at verifyENOENT (C:\git\angular-electron-dream-starter\node_modules\
cross-spawn\lib\enoent.js:46:16)
at ChildProcess.cp.emit (C:\git\angular-electron-dream-starter\node_modules\
cross-spawn\lib\enoent.js:33:19)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

   - *Please tell us about your environment:*

window 10, node 6.11.0 and npm 3.10.10

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/colinskow/angular-electron-dream-starter/issues/5>, or mute
the thread

**Comment by colinskow** [comment]
This should be fixed now.
